services:
  frontend:
    build:
      context: .
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/hal9k/projects:/home/hal9k/projects:ro
    environment:
      CONTROL_API_BASE_URL: http://127.0.0.1:8010
      APP_NAME: Introspect
      APP_ENV: production
      APP_PORT: "40080"
    restart: unless-stopped
